name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Build the Docker Image
      working-directory: guestbook-go
      run: docker build -t app .
        
    - name: Login to DockerHub Registry
      run: winpty docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_SECRET }} --password-stdin

    - name: Push Image to DockerHub Registry
      run: |
        docker tag app varshilsoni/varshil_ridecell_assignment
        docker push varshilsoni/varshil_ridecell_assignment
